language: java

jdk:
  - openjdk15

sudo: false

env:
  global:
    - CODECOV_TOKEN="77a9a3b3-b6b3-4ec1-be45-f023e4bb406a"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - dla-raboti5@yandex.ru
    on_success: never # default: change
    on_failure: always # default: always